# Following unit test convention found in http://en.wikibooks.org/wiki/Ruby_Programming/Unit_testing
require 'test/unit'
require 'tc_symbol'
require 'tc_suit'
require 'tc_card'
require 'tc_hand'
require 'tc_deck'
require 'tc_player'
require 'tc_display'
require 'tc_game'
